// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hnmvaolmenvymvohziuh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhubXZhb2xtZW52eW12b2h6aXVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MzE0ODcsImV4cCI6MjA2MzUwNzQ4N30.JjO_Pv7alsvJrMpQAeyPypwcZmvO4hW5rEr_WzNaREs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);